// // Generated by Selenium IDE
// require('chromedriver');
// const { Builder, By, Key, until } = require('selenium-webdriver')
// const assert = require('assert')
// const { expect } = require('chai');

// describe('DefaultTest', function() {

//     // let driverPromise
//     // let vars
//     // beforeEach(async function() {
//     //     driverPromise = await new Builder().forBrowser('chrome').build()
//     //     vars = {}
//     // })
//     // afterEach(async function() {
//     //     await driverPromise.quit();
//     // });
//     // it('should go to nehalist.io and check the title', async() => {
//     //     await driver.get('https://www.google.com');
//     //     await driver.findElement(By.name('q')).sendKeys('hola');
//     //     await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
//     //         //await driver.wait(until.elementLocated(By.id('search')));
//     //     await driver.findElement(By.linkText('¡HOLA! México')).click();
//     //     const title = await driver.getTitle();
//     //     expect(title).to.equal('¡HOLA! México: notas de famosos, moda y belleza - hola.com');
//     // });
//     it('log', async function() {
//         let driverPromise = new Builder()
//             .forBrowser('chrome')
//             .build();
//         driverPromise.then(driver => driver.get('https://qa.timtravel.app/'))
//             .then(() => driver.get(""))
//             .then(() => driver.findElement(By.id("username")).click())
//             .then(() => driver.findElement(By.id("username")).sendKeys("ignacio"))
//             .then(() => driver.findElement(By.id("password")).sendKeys("Igno_$19"))
//             .then(() => driver.findElement(By.css(".btn")).click())
//             .then(() => driver.findElement(By.css(".label")).click())
//             .then(() => driver.quit())

//         // await driver.findElement(By.name("provider_id")).click()
//         // await driver.findElement(By.name("provider_id")).sendKeys("Da")
//         // await driver.findElement(By.css("#typeahead-63-9519-option-0 .ng-binding:nth-child(3)")).click()
//         // await driver.findElement(By.css("div:nth-child(3) > .ng-scope:nth-child(1) > .ng-scope > .ui-select-container .select2-chosen:nth-child(2)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-4-0 > .select2-result-label")).click()
//         // await driver.findElement(By.name("booking_name")).click()
//         // await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-scope > .ng-scope > .ui-select-container .select2-chosen:nth-child(2)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-5-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-scope > .ng-pristine .select2-chosen:nth-child(2)")).click()
//         // await driver.findElement(By.css(".ui-select-choices-row-inner")).click()
//         // await driver.findElement(By.css(".col-md-3:nth-child(1) .select2-chosen:nth-child(2)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-1-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".col-md-3:nth-child(2) .label:nth-child(1)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-2-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".ng-scope > .ng-untouched > .select2-choice")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-3-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".input-wrap > .ng-valid .select2-chosen:nth-child(2)")).click()
//         // await driver.findElement(By.css(".ui-select-choices-row-inner")).click()
//         // await driver.findElement(By.css(".select2-default > .ng-binding")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-7-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".btn-success")).click()
//         // await driver.findElement(By.css(".btn-lg:nth-child(2)")).click()
//         // await driver.findElement(By.css(".table:nth-child(2) .btn > .ng-binding")).click()
//         // await driver.findElement(By.css(".form-group:nth-child(6) .select2-chosen:nth-child(1)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-11-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".ng-invalid > .select2-choice > .ng-binding")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-10-0 > .select2-result-label")).click()
//         // await driver.executeScript("window.scrollTo(0,0)")
//         // await driver.findElement(By.css(".ng-pristine > .fa")).click()
//         // await driver.findElement(By.css(".header-view .ng-binding:nth-child(3)")).click()
//         // await driver.findElement(By.css("tbody > .ng-scope:nth-child(1) > .ng-binding:nth-child(2)")).click()
//         // await driver.findElement(By.css(".ng-scope:nth-child(3) > .calendar-cell:nth-child(3) .extras")).click()
//         // await driver.findElement(By.css("div:nth-child(2) > .btn-success")).click()
//         // await driver.findElement(By.css(".nav-link > .ng-binding")).click()
//         // await driver.findElement(By.css(".btn-success:nth-child(2)")).click()
//         // await driver.findElement(By.name("name")).click()
//         // await driver.findElement(By.name("name")).sendKeys("Royland")
//         // await driver.findElement(By.css(".modal-body")).click()
//         // await driver.findElement(By.name("last_name")).click()
//         // await driver.findElement(By.name("last_name")).sendKeys("Solis")
//         // await driver.findElement(By.css(".col-md-4:nth-child(2) .select2-chosen:nth-child(1)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-18-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".ng-invalid > .select2-choice > .ng-binding")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-19-0 > .select2-result-label")).click()
//         // await driver.findElement(By.name("phone")).click()
//         // await driver.findElement(By.name("phone")).sendKeys("88026523")
//         // await driver.findElement(By.name("email")).click()
//         // await driver.findElement(By.name("email")).sendKeys("rsolicha@gmail.com")
//         // await driver.findElement(By.name("height")).click()
//         // await driver.findElement(By.name("height")).sendKeys("1.50")
//         // await driver.findElement(By.css(".col-md-2:nth-child(3) .select2-chosen:nth-child(1)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-20-0 > .select2-result-label")).click()
//         // await driver.findElement(By.name("weight")).click()
//         // await driver.findElement(By.name("weight")).sendKeys("50")
//         // await driver.findElement(By.css(".select2-default > .ng-binding")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-21-0 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".col-md-2:nth-child(6) .select2-chosen:nth-child(2)")).click()
//         // await driver.findElement(By.css("#ui-select-choices-row-21-1 > .select2-result-label")).click()
//         // await driver.findElement(By.css(".moment-picker-input")).click()
//         // await driver.findElement(By.css(".header-view .ng-binding:nth-child(2)")).click()
//         // await driver.findElement(By.css("thead .ng-binding:nth-child(1)")).click()
//         // await driver.findElement(By.css("thead .ng-binding:nth-child(1)")).click()
//         // await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(2)")).click()
//         // await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(3)")).click()
//         // await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(4)")).click()
//         // await driver.findElement(By.css(".btn-primary")).click()
//         // await driver.findElement(By.css(".btn:nth-child(3)")).click()
//     })

// });